stages:
  prepare:
    cmd: python src/prepare.py data/row/dataset.csv data/prepared
    deps:
      - data/row/dataset.csv
      - src/prepare.py
    outs:
      - data/prepared

  train:
    cmd: >-
      python src/train.py
      --train_data data/prepared/train.csv
      --test_data data/prepared/test.csv
    deps:
      - data/prepared/train.csv
      - data/prepared/test.csv
      - src/train.py
    outs:
      - model.pkl
      - metrics.json
      - confusion_matrix.png